---
abstract: 'Command line apps for Chado relational database '
author:
  - 'Siddhartha Basu <biosidd@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Modware-Loader
recommends:
  Child: 0.009
  Text::TablularDisplay: 1.33
  XML::LibXML: 1.70
  XML::Simple: 2.18
requires:
  Bio::Chado::Schema: 0.20000
  Bio::GFF3::LowLevel: 1.5
  BioPortal::WebService: v1.0.0
  DBD::Oracle: 1.52
  Email::Sender::Simple: 0.102370
  Email::Simple: 2.10
  Email::Valid: 0.184
  File::Find::Rule: 0.32
  Log::Log4perl: 1.40
  Math::Base36: 0.10
  MooseX::App::Cmd: 0.09
  MooseX::Attribute::Dependent: v1.1.2
  MooseX::ConfigFromFile: 0.10
  MooseX::Event: v0.2.0
  MooseX::Getopt: 0.56
  MooseX::Types::Path::Class: 0.06
  Spreadsheet::WriteExcel: 2.37
  Tie::Cache: 0.17
  perl: 5.010
version: 1.1.0
